#!/usr/local/bin/ruby -w

CONFIG_PATH = './.project'

unless File.exist?(CONFIG_PATH)
  abort('Please ensure .project exists in project container directory.')
end
repos = File.read(CONFIG_PATH).split("\n").map(&:strip)

repos.each do |r|
  command ="cd #{r};git pull;"
  if branch = ARGV[0]
    command += "git checkout #{branch}"
  end
  puts `#{command}`
end
