#!/usr/local/bin/ruby -w

CONFIG_PATH = './.branches'

safe_branches = ['master', 'devel', 'develop', 'test', 'prod', 'production']

if File.exist?(CONFIG_PATH)
  configured_branches = File.read(CONFIG_PATH).split("\n").map(&:strip)
  safe_branches += configured_branches
  safe_branches.uniq!
end

unwanted_branches = `git branch`.split("\n").map(&:strip).select do |b|
  !b.match(/\*/) &&
    !safe_branches.include?(b)
end

if unwanted_branches.empty?
  puts 'No branches to clean.'
else
  puts `git branch -D #{unwanted_branches.join(" ")}`
end
